name: tests
on:
  push:
  pull_request:
  schedule:
    - cron: 0 4 * * MON,FRI
jobs:
  vm:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Build
        run: make

      - name: Run tests
        run: sudo tests/run

  container:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        container:
          - docker.io/amd64/ubuntu:devel
          - docker.io/amd64/debian:sid
          - registry.fedoraproject.org/fedora:latest
          - registry.fedoraproject.org/fedora:rawhide

    container:
      image: ${{ matrix.container }}
      options: --privileged
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install build and test dependencies
        run: |
          if type apt >/dev/null 2>&1; then
              apt-get update
              DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends gcc libc-dev make python3 btrfs-progs
          else
              dnf install -y gcc glibc-devel make python3 btrfs-progs
          fi

      - name: Build
        run: make

      # iterating through all mounts does not work in a container
      - name: Run currentmount tests
        run: |
          export AUTOPKGTEST_TMP=$(mktemp -d)
          export PATH=$(pwd):$PATH
          tests/fatrace-currentmount

      - name: Run btrfs tests
        run: |
          export AUTOPKGTEST_TMP=$(mktemp -d)
          export PATH=$(pwd):$PATH
          tests/fatrace-btrfs
